#!/usr/bin/env bash
# a script that transfers file from client to a server using scp

if [ $# -lt 4  ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_TO_TRANSFER=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

scp -o "StrictHostKeyChecking=no" -i $SSH_KEY $FILE_TO_TRANSFER $USERNAME@$SERVER_IP:~/
