#!/usr/bin/env bash
# This script installs and configures Nginx to serve 'Hello World' on port 80
# and redirects /redirect_me to another page with a 301 Moved Permanently status.

if [ "$(id -u)" != "0" ]; then
    exit 1
fi

apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
rm -f /etc/nginx/sites-enabled/default

cat << EOF > /etc/nginx/sites-available/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
            }

        location /redirect_me {
                return 301 https://github.com/x17-green;
            }
        }
EOF

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
nginx -t
service nginx restart

