#!/usr/bin/env bash
# A bash script displaying "Best School"
# 10 time with a Special 4th and 8th
# iteration

i=1
while [ $i -le 10 ]; do
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i+1))
done
